<?php 
    session_start();

    if(isset($_GET['logout'])) {
        session_destroy();
        unset($_SESSION['username']);
        header("location: index.php");
    }
?>
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Story</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Allerta+Stencil" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
</head>
<body>
    <nav class="topnav">
        <a href="https://www.marvel.com"><img src = "Images/indeximages.png" alt = "Avengers"></a>
        <ul>
            <li><a href = "index.php">About</a></li>
            <li><a href = "characters.php">Characters</a></li>
            <?php if (isset($_SESSION['username'])) : ?>
                <li><a href="index.php">Welcome <strong><?=$_SESSION['username']?></strong>, <?=$_SESSION['success']?></a></li>
                <li><a href="index.php?logout='1'" style="color: red;">Logout</a></li>
            <?php else: ?>
                <li><a href = "share.php">Share</a></li>      
                <li><a href = "#">Something</a></li>
                <li><a href = "login.php">Login</a></li>
            <?php endif ?>
        </ul>
    </nav>
    <div>
        <h1>The Avengers</h1>
        <p>Nick Fury assembles the team when an unexpected threat associated with Thor's brother Loki and the Tesseract appears. The team initially have difficulty and refusal to obey each other; for example, Tony Stark is reluctant to working under the command of Captain America, Thor demands that Loki is his responsibility and the team is uncomfortable with the presence of Bruce Banner. When Loki attempts to destroy the team and promote his godlike supremacy to Earth in a public way, the Avengers depart from S.H.I.E.L.D.'s command and rally in defense of New York as it is invaded by the extraterrestrials known as the Chitauri. Captain America takes command of the team and they each work to suppress the invasion force. The Hulk beats Loki into submission and Iron Man sends a nuclear weapon fired by the World Security Council into the portal through which the aliens enter Earth and their fleet is destroyed, breaking the neural connection with their ground troops and instantly killing them. The team take Loki as their prisoner and Thor takes both Loki and the Tesseract back to Asgard. The team disbands but agrees to reassemble when another global threat requires their combined efforts.</p>

        <h1>Avengers: Age of Ultron</h1>
        <p>After the fall of S.H.I.E.L.D. Loki's Scepter fell into the hands of HYDRA. The threat it posed drew the Avengers back together in a desperate worldwide hunt. The Avengers had the financial backing of Tony Stark. Using the former Stark Tower, now renamed Avengers Tower, as their headquarters. After many months they tracked it to a HYDRA research facility run by Wolfgang von Strucker in Sokovia and launched an all out assault to recover it. The Avengers also noted that they were being harassed by two "enhanced" during the operation, but together with Stark's Iron Legion the team soon overthrew the HYDRA soldiers and reclaimed the sceptre. Tony appealed to Thor to have two days to study the alien device before it was relocated to Asgard, which Thor agreed to, and then the team unanimously agreed to celebrate their victory.</p>

        <p>Back in New York at Avengers Tower, Tony began to unravel the mysteries of the sceptre. Tony and Bruce Banner discovered that its core held something akin to a powerful computer and deduced that HYDRA had been trying to use it to create artificial intelligence. With this knowledge he had the epiphany that he might be able to provide real adaptive thought to his Iron Legion in what he called his Ultron Program. He and Bruce then left J.A.R.V.I.S. to continue investigating while he rejoined his team for a night of celebration. The party was huge and the Avengers gathered many of their friends for the night. When the revelry had died down, and most of the guests had left, the remaining men took turns trying to lift Mjölnir. This activity was interrupted by the appearance of a wrecked Iron Legion drone. It quickly became apparent that this was being operated by a rogue artificial intelligence, and the name it claimed for itself was "Ultron". Ultron and a number of other Iron Legion drones, then attacked the small group. They rallied and beat it back, but not before one of the Iron Legion made off with the sceptre during the confusion. Thor promptly turned on Stark demanding to know why he had created such a thing, to which Tony pointed out that they needed a way to deal with threats on the scale of the Chitauri.</p>

        <p>The Avengers traced Ultron's movements to a salvage yard on the coast of Africa where Ulysses Klaue dealt in the lucrative end of black market trading. So began a three way battle between Klaue's men after Ultron severed his arm, the Avengers, and the Ultron Sentries. Ultron also had the advantage of the pair of enhanced that the Avengers had encountered in Sokovia, the siblings Wanda and Pietro Maximoff. Pietro's speed allowed him to devastate the ranks of Klaue's men, while Wanda ravaged the minds of the Avengers themselves. When she at last reached Banner, her illusions caused him to fly into a rage that he then directed towards the populace of Johannesburg, and then she Ultron and Pietro made their escape. With most of the Avengers out of action fighting their own inner demons, Tony was left to attend to the problem of a rampaging Hulk on his own. He asked Veronica, a shuttle that could deploy numerous pieces of a heavy duty Iron Man armor. Tony in the Hulkbuster Armor afforded him the physical power to subdue the Hulk, but the public relations damage had been done, leaving Bruce in a morose state. Clint Barton took the group to a safehouse to recover, soon revealing that it was actually his family home. There they met Nick Fury, who began reorienting their thinking and fomenting new strategic considerations within the shattered ranks. Banner and Romanoff had both been psychologically scarred by their encounter Wanda and contemplated simply leaving. Tensions ran high between Tony and Steve Rogers, and Thor had been given a glimpse of something very troubling and departed the group to investigate further.</p>

        <p>Ultron's plan to use the sceptre to create a final evolutionarily pure form for himself had become clear, and the last piece of that puzzle was with Dr. Helen Cho in South Korea. They raced for Seoul, and found Ultron deep into an attempt to load his consciousness into a new android body. Their interference forced Ultron to flee, but the group managed to separate the android body from the robot before he escaped again, and Stark, and Barton, took it back to New York. Rogers on the other hand, found himself joined by the Maximoff twins on the street of Seoul after Wanda had discovered Ultron's true intent. Romanoff had not been so lucky, and having been rendered unconscious in the confrontation soon found herself imprisoned by Ultron in Sokovia. Once they were back in New York, Stark and Banner bickered over the android body. Stark wanted to load J.A.R.V.I.S. into it, but Banner didn't trust his judgement. The dispute continued until it was interrupted by the arrival of Rogers and the Maximoff twins, whereupon Pietro ended it by simply unplugging the entire system. Then Thor made a surprise appearance and promptly bathed the android in lightning. It awoke in the surge and cast him aside. The Avengers and the Maximoff twins all moved to counter the android but halted when it stopped by a window to gaze out upon the city. It quickly became apparent that the android was no threat, especially fostering trust in Thor when it hefted Mjolnir with ease. The assembled group then compared stories, and Thor reported news of his vision that the energy core of the sceptre had actually contained the Mind Stone, an item of incredible power and one of the legendary Infinity Stones. That gem was now resting in the forehead of the android, which soon began referring to itself as Vision.</p>

        <p>The Avengers and their three allies turned their attention back to Ultron and Sokovia. Banner went alone to extract Romanoff from her prison, and the others faced off against Ultron. While Ultron's plan to divide and exterminate the Avengers had failed, its plans for the human race were about to be fully revealed. Devices planted within the city engaged, drawing a sizeable portion of it into the sky. The assembled heroes, with Banner and Romanoff back amongst them, fought back against the amassed ranks of Ultron's robot legion. James Rhodes, suited up as War Machine, and a recently repaired helicarrier with him, also eventually joined the battle. After clearing most of the Ultron robots from the city now risen above the cloud layer, the heroes began evacuating the trapped populace in personnel transports sent from the helicarrier. Barton was caught under the guns of the Avengers' own quinjet however, with Ultron at the controls, and only the intervention of Pietro saved him. Pietro had saved both Barton and a boy with this final act, but at the cost of his own life when the quinjet's gunfire tore through his chest. The Vision finally confronted Ultron alone after the Hulk had flung the robot from the quinjet. Heavily damaged, Ultron was no match for the android, and fell to the Vision's power. With Ultron's defeat, the group began an inevitable dissolution. The Hulk switched off the quinjet's communications, leaving it to fly him clear of the scene. Thor and Stark each had their own agendas to pursue, with Thor needing to investigate the matter of yet another Infinity Stone coming within reach. Barton meanwhile had a new baby to attend to and left to return to his family.</p>

        <p>Despite their losses, the Avengers were also to be born anew. Steve and Romanoff proceeded to a new Avengers facility in New York, and welcomed a new quartet to the fold. They were joined by the Vision, Wanda Maximoff, James Rhodes aka War Machine, and Steve's recent companion, Sam Wilson aka the Falcon.</p>
        
        <h1>Avengers: Infinity War</h1>
        <p>Having acquired the Power Stone from the planet Xandar, Thanos and his lieutenants—Ebony Maw, Cull Obsidian, Proxima Midnight, and Corvus Glaive—intercept a spaceship carrying the last survivors of Asgard. As they extract the Space Stone from the Tesseract, Thanos subdues Thor, overpowers Hulk, and kills Loki. Heimdall sends Hulk to Earth using the Bifröst before being killed. Thanos departs with his lieutenants and obliterates the ship.</p>

        <p>Hulk crash-lands at the Sanctum Sanctorum in New York City, reverting to Bruce Banner. He warns Stephen Strange and Wong about Thanos' plan to kill half of all life in the universe; in response, Strange recruits Tony Stark. Maw and Obsidian arrive to retrieve the Time Stone from Strange, drawing the attention of Peter Parker. Maw captures Strange, but fails to take the Time Stone due to an enchantment. Stark and Parker pursue Maw's spaceship, Banner contacts Steve Rogers, and Wong stays behind to guard the Sanctum.</p>

        <p>In Edinburgh, Midnight and Glaive ambush Wanda Maximoff and Vision in order to retrieve the Mind Stone in Vision's forehead. Rogers, Natasha Romanoff, and Sam Wilson rescue them and take shelter with James Rhodes and Banner at the Avengers Compound. Vision offers to sacrifice himself by having Maximoff destroy the Mind Stone to keep Thanos from retrieving it. Rogers suggests they travel to Wakanda, which he believes has the resources to remove the stone without destroying Vision.</p>

        <p>The Guardians of the Galaxy respond to a distress call from the Asgardian ship and rescue Thor, who surmises Thanos seeks the Reality Stone, which is in the possession of the Collector on Knowhere. Rocket and Groot accompany Thor to Nidavellir, where they and Eitri create a battle-axe capable of killing Thanos. On Knowhere, Peter Quill, Gamora, Drax, and Mantis find Thanos with the Reality Stone already in his possession. Thanos kidnaps Gamora, his adoptive daughter, who reveals the location of the Soul Stone to save her captive adoptive sister Nebula from torture. Thanos and Gamora travel to Vormir, where Red Skull, keeper of the Soul Stone, informs him the stone can only be retrieved by sacrificing someone he loves. Thanos reluctantly kills Gamora, earning the stone.</p>

        <p>Nebula escapes captivity and asks the remaining Guardians to meet her on Thanos' destroyed homeworld, Titan. Stark and Parker kill Maw and rescue Strange. Landing on Titan, they meet Quill, Drax, and Mantis. The group forms a plan to remove Thanos' Infinity Gauntlet after Strange uses the Time Stone to view millions of possible futures, seeing only one in which Thanos loses. Thanos arrives, justifying his plans as necessary to ensure the survival of a universe threatened by overpopulation. The group subdues him until Nebula deduces that Thanos has killed Gamora. Enraged, Quill attacks him, allowing Thanos to break the group's hold and overpower them. Stark is seriously wounded by Thanos, but is spared after Strange surrenders the Time Stone to Thanos.</p>

        <p>In Wakanda, Rogers reunites with Bucky Barnes before Thanos' army invades. The Avengers, alongside T'Challa and the Wakandan forces, mount a defense while Shuri works to extract the Mind Stone from Vision. Banner, unable to transform into the Hulk, fights in Stark's Hulkbuster armor. Thor, Rocket, and Groot arrive to reinforce the Avengers; Midnight, Obsidian, and Glaive are killed and their army is routed. Thanos arrives and despite Maximoff's attempt to destroy the Mind Stone, removes it from Vision's head, killing him.</p>

        <p>Thor severely wounds Thanos, but Thanos activates the completed Infinity Gauntlet and teleports away. Half of all life across the universe disintegrates, including Barnes, T'Challa, Groot, Maximoff, Wilson, Mantis, Drax, Quill, Strange, and Parker, as well as Maria Hill and Nick Fury, although Fury is able to transmit a signal first. Stark and Nebula remain on Titan while Banner, M'Baku, Okoye, Rhodes, Rocket, Rogers, Romanoff, and Thor are left on the Wakandan battlefield. Meanwhile, Thanos watches a sunrise on another planet.</p>
    </div>
</body>
</html>